title: Sean-Limpias
description: >
  In this blog I will go over some things that have helped me along the way of my Cyber Security journey.

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
