title: Sean-Limpias
description: >- 
  In this blog I will go over some things that have helped me along the way of my Cyber Security journey.
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
